name: Windows Server 2022 Remote Virtual Machine
on:
  workflow_dispatch:
    inputs:
      office:
        description: 'Install Microsoft 365?'
        default: false
        required: false
        type: boolean

      qgis:
        description: 'Install QGIS?'
        default: false
        required: false
        type: boolean

      arcgis:
        description: 'Install ArcGIS?'
        default: false
        required: false
        type: boolean

      globalmapper:
        description: 'Install GlobalMapper?'
        default: false
        required: false
        type: boolean

      inkscape:
        description: 'Install Inkscape?'
        default: false
        required: false
        type: boolean

jobs:
  build:

    runs-on: windows-latest
    name: 'Set up a Windows VM'
    timeout-minutes: 9999

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Installing and configuring Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        choco install ngrok | Out-Null
        ngrok authtoken $Env:NGROK_AUTH_TOKEN

    - name: Activating RDP access.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Starting Ngrok tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "ngrok tcp 3389"'

    - name: Launching the start script
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/start.ps1').Content

    - name: Configuration
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/config.ps1').Content

    - name: Install Microsoft 365.
      if: ${{ github.event.inputs.office == 'true' }}
      run: |
        choco install office365business | Out-Null
      continue-on-error: true

    - name: Install QGIS.
      if: ${{ github.event.inputs.qgis == 'true' }}
      run: |
        choco install qgis | Out-Null
      continue-on-error: true

    - name: Install Inkscape.
      if: ${{ github.event.inputs.inkscape == 'true' }}
      run: |
        choco install inkscape | Out-Null
      continue-on-error: true

    - name: Installing ArcGIS
      if: ${{ github.event.inputs.arcgis == 'true' }}
      run: |
        Invoke-WebRequest 'https://www.googleapis.com/drive/v3/files/1pBwf4I3dehDQtpjQZYQwvKfw5CE3aynq?alt=media&key=AIzaSyBD8tY90tF5DojRDNgAHN00gfoTCNOiuAI' -OutFile "${Env:TEMP}\ArcGIS_Setup.zip"
        Expand-Archive -Path "${Env:TEMP}\ArcGIS_Setup.zip" -DestinationPath "C:\ArcGIS\"
        Start-Process -FilePath "C:\ArcGIS\Extract\Setup.exe" -ArgumentList "ESRI_LICENSE_HOST=GIS ACCEPTEULA=yes SOFTWARE_CLASS=Professional SEAT_PREFERENCE=Float DESKTOP_CONFIG=TRUE INSTALLDIR1=D:\python27 /qb"
        Copy-Item "C:\ArcGIS\Originals\AfCore.dll" -Destination "${Env:programfiles(x86)}\ArcGIS\Desktop10.8\bin\"
      continue-on-error: true

    - name: Installing Global Mapper
      if: ${{ github.event.inputs.globalmapper == 'true' }}
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/install_globalmapper.ps1').Content
      continue-on-error: true

    - name: Setup TMATE session
      uses: mxschmitt/action-tmate@v3
      continue-on-error: true
